### PR TITLE
Flatten component structure

### PR DESCRIPTION
**Pull request by alindeman**
This seems to allow this project to be cloned directly into `custom_components/` without having to muck with adding `__init__.py` to `site-packages/`.

I tried not to change much else other than bits necessary to get this working, but I'd be happy to help with this codebase a bit more afterward. Let me know what you think.

### CODE REVIEW

**Comment by apetrycki** [comment]
This looks OK to me. The question I would have is if the homeassistant group wants it this way. I thought I remembered seeing some documentation that they wanted to keep the integration separate from the API code base.

**Comment by alindeman** [comment]
> This looks OK to me. The question I would have is if the homeassistant group wants it this way. I thought I remembered seeing some documentation that they wanted to keep the integration separate from the API code base.

I'm not an expert at Home Assistant components yet, but it does seem to be pretty standard to include all the files in a `custom_components/foo` directory. Some examples:

* https://github.com/custom-components/authenticated
* https://github.com/custom-components/weatheralerts

We could consider actually having a `custom_components/daikinskyport` directory in this repo if you wanted.

I think it's important to avoid modifications to `site-packages/` for folks that run Home Assistant in (for example) a Docker container that is typically considered immutable.

Let me know what you think or if I can research further.

**Comment by apetrycki** [comment]
Eventually, I would like to get this into the base HA repository as a standard component.  Having the subdirectory is probably the best way to do it so things can be split later if necessary.  My guess is they want to do this so it's less code that has to be maintained in HA.  A lot of updates can be made by simply changing the version in the manifest.

**Comment by alindeman** [comment]
> Eventually, I would like to get this into the base HA repository as a standard component. Having the subdirectory is probably the best way to do it so things can be split later if necessary. My guess is they want to do this so it's less code that has to be maintained in HA. A lot of updates can be made by simply changing the version in the manifest.

Gotcha. Would you like me to update this PR to move the files into a `custom_components/daikinskyport` directory?

**Comment by apetrycki** [comment]
That would be great!  Thanks for all the help!

**Comment by apetrycki** [comment]
@xeqi has provided the alternative way in request #2, so I accepted that and will close this.  Thanks again for working on this @alindeman!

**Pull request closed without merging**
